# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QMainWindow
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QDoubleValidator
from PyQt5.QtWidgets import QMainWindow, QLabel, QGridLayout, QWidget, QLineEdit
from PyQt5.QtCore import QSize, QRegExp
from PyQt5.QtGui import QRegExpValidator

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.category = QtWidgets.QLabel(self.centralwidget)
        self.category.setGeometry(QtCore.QRect(20, 30, 101, 41))
        self.category.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.category.setObjectName("category")
        self.insert_btn_money = QtWidgets.QPushButton(self.centralwidget)
        self.insert_btn_money.setGeometry(QtCore.QRect(20, 80, 201, 41))
        self.insert_btn_money.setStyleSheet("alternate-background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5"
                                            ", "
                                            "radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), "
                                            "stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));")
        self.insert_btn_money.setObjectName("insert_btn_money")
        MainWindow.setCentralWidget(self.centralwidget)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        ipRange = "(?:[0-1]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])"  # Часть регулярного выржение
        # Само регулярное выражение
        ipRegex = QRegExp("^" + ipRange + "\\." + ipRange + "\\." + ipRange + "\\." + ipRange + "$")
        ipValidator = QRegExpValidator(ipRegex, self)  # Валидатор для QLineEdit
        grid_layout = QGridLayout(self)
        grid_layout.addWidget(QLabel("Введите IP-адрес", self), 0, 0)
        lineEdit = QLineEdit()
        lineEdit.setValidator(ipValidator)  # Устанавливаем валидатор
        grid_layout.addWidget(lineEdit, 0, 1)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "financial assistant"))
        self.category.setText(_translate("MainWindow", "категория"))
        self.insert_btn_money.setText(_translate("MainWindow", "Insert"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
